### PR TITLE
Add Auto Discovery support for Laravel 5.6 & Add helpers for assets usage.

### PR DESCRIPTION
**Pull request by rizalfakhri**

### CODE REVIEW

**Comment by rizalfakhri12** [comment]
Ksip AKMJ

**Comment by nauvalazhar** [comment]
Tambahin support folder bos

**Comment by rizalfakhri12** [comment]
nyuruh?

**Comment by nauvalazhar** [comment]
Kapan lagi nyuruh orang kaga puasa

**Pull request merged**
